@URL = http://localhost:3000

### get all users
GET {{URL}}/users
# search a user
###
GET {{URL}}/users/search?q=John

### get a user by id
GET {{URL}}/users/3
### create a user

POST {{URL}}/users
Content-Type: application/json

{
      "name": "Jane Smith",
      "email": "jane@example.com",
      "password": "secret",
      "createdAt": "2023-10-01T12:00:00Z",
      "updatedAt": "2023-10-01T12:00:00Z",
      "role": "admin"
    }

### update a user
PATCH  {{URL}}/users/1
Content-Type: application/json

{
      "name": "Jane Doe"
}
### delete a user
DELETE {{URL}}/users/1

### mechanics
### get all mechanics
GET {{URL}}/mechanics

### update a mechanic
PATCH {{URL}}/mechanics/1
Content-Type: application/json

{
      "name": "Updated Mechanic Name"
}
### delete a mechanic
DELETE {{URL}}/mechanics/1
### create a mechanic
POST {{URL}}/mechanics
Content-Type: application/json

{
      "name": "New Mechanic",
      "email": "newmechanic@example.com",
      "specialization": "Engine Repair",
      "phone": 1234567890,
      "location": "123 Main St, Springfield",
      "experience": 5
}
### get a mechanic by id
GET {{URL}}/mechanics/2     

get all feedbacks
GET {{URL}}/feedbacks
### create feedback
POST {{URL}}/feedbacks
Content-Type: application/json

{
      "user_id": 1,
      "comment": "Excellent service!",
      "rating": 5,
      "mechanic_id": 1,
      "feedback_id": 1
}