@URL = http://localhost:8000
###


### get all users
GET {{URL}}/users/
# search a user
###
GET {{URL}}/users/search?query=jan

### get a user by id
GET {{URL}}/users/16


### create a user
POST {{URL}}/users
Content-Type: application/json

{
      "name": "Janewq Smith",
      "email": "jfaaneh@exaample.com",
      "password": "secret",
      "role": "admin"
    }

### update a user
PATCH  {{URL}}/users/16
Content-Type: application/json

{
      "name": "Jane Doe"
}
### delete a user
DELETE {{URL}}/users/16

### mechanics
### get all mechanics
GET {{URL}}/mechanics

### update a mechanic
PATCH {{URL}}/mechanics/2
Content-Type: application/json

{
      "name": "Updated Mechanic Name"
}
### delete a mechanic
DELETE {{URL}}/mechanics/1
### create a mechanic
POST {{URL}}/mechanics
Content-Type: application/json

{
      "name": "New Mechanic",
      "email": "newhmechaaanic@example.com",
      "phone": 1234567890,
      "location": "123 Main St, Springfield"
}
### get a mechanic by id
GET {{URL}}/mechanics/3  
###
GET {{URL}}/feedbacks
### create feedback
POST {{URL}}/feedbacks
Content-Type: application/json

{
      "user": 6,
      "comment": "Excellent service!",
      "rating": 5
} 
###GET SERVICES
GET {{URL}}/services
### create a service
POST {{URL}}/services/
Content-Type: application/json

{
  "name": "Oil Change",
  "description": "Full synthetic oil change service",
  "price": 49.99,
  "duration": 60,
  "categoryId": 1,
  "mechanicIds": [1, 2]
}


### LOGIN a new user
POST {{URL}}/auth/signin
Content-Type: application/json

{
  "email": "jfaaneh@exaample.com",
  "password": "secret"
}
### logout a user
GET  {{URL}}/auth/signout/17
Content-Type: application/json

{
  "email": "jfaaneh@exaample.com"
}
