services:  
  vehicle-breakdown-db:
    image: postgres:15-alpine
    container_name: vehicle-breakdown-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "@Antoh2644"
      POSTGRES_DB: vehicle_breakdown_db
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5433:5432"
    networks:
      - vehicle-breakdown-network
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
      image: redis:8.0-alpine
      container_name: vehicle-breakdown-redis
      restart: unless-stopped
      environment:
        - REDIS_URL=redis://:${REDIS_PASSWORD}@vehicle-breakdown-redis:6379
      command: ["redis-server", "--requirepass", "${REDIS_PASSWORD:-antony}"]
      ports:
      - "6379:6379"
      networks:
        - vehicle-breakdown-network
      volumes:
        - redis-data:/data
      healthcheck:
          test: ["CMD-SHELL", "redis-cli -a ${REDIS_PASSWORD} ping"]
          interval: 10s
          timeout: 5s
          retries: 5
  vehicle-breakdown-api:
      container_name: vehicle-breakdown-api
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "8000:8000"
      environment:
        - NODE_ENV=development
        - PORT=8000
        - REDIS_PASSWORD=antony
        - PG_HOST=vehicle-breakdown-db
        - PG_PORT=5432
        - PG_USERNAME=postgres
        - PG_PASSWORD=@Antoh2644
        - PG_DATABASE=vehicle_breakdown_db
        - PG_AUTOSYNC=true
        - PG_AUTOLOAD=true
        - REDIS_URL=redis://:antony@vehicle-breakdown-redis:6379
        - JWT_ACCESS_TOKEN_SECRET=your-access-token-secret
        - JWT_ACCESS_TOKEN_EXPIRATION_TIME=15m
        - JWT_REFRESH_TOKEN_SECRET=your-refresh-token-secret
        - JWT_REFRESH_TOKEN_EXPIRATION_TIME=7d
      depends_on:
         redis:
           condition: service_healthy
         vehicle-breakdown-db:
           condition: service_healthy
      networks:
        - vehicle-breakdown-network
      volumes:
        - .:/app
        - /app/node_modules
volumes:
  pgdata:
    name: vehicle-breakdown-pgdata
    driver: local
  redis-data:
    name: vehicle-breakdown-redis-data
    driver: local
networks:
  vehicle-breakdown-network:
    driver: bridge

    
